version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-1"

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y amazon-linux-extras
      - amazon-linux-extras install epel -y
      - yum install -y git
      - curl -sL https://rpm.nodesource.com/setup_14.x | bash -
      - yum install -y nodejs
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py
      - pip install awsebcli
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t webapp .
  post_build:
    commands:
      - echo Deploying to Elastic Beanstalk...
      - eb init -p docker toto-blog-test --region $AWS_DEFAULT_REGION -i
      - eb use Toto-blog-test-env
      - eb deploy
artifacts:
  files:
    - "**/*"
